{% set name = "dash-html-components" %}
{% set filename = "dash_html_components" %}
{% set version = "0.14.0" %}
{% set sha256 = "919da2c0c209520abf9478d71ccd7d273130025a37677c2b1eaf1a41cd47f75b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - dash  # not listed in the setup.py

test:
  imports:
    - dash_html_components
    - dash_html_components.version

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash-html-components
  license: MIT
  license_family: MIT
  # TODO : Update this once plotly packages it correctly:
  # https://github.com/plotly/dash-html-components/pull/46
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Dash UI HTML component suite'

extra:
  recipe-maintainers:
    - moorepants
