{% set name = "dash-html-components" %}
{% set filename = "dash_html_components" %}
{% set version = "2.0.0" %}
{% set sha256 = "8703a601080f02619a6390998e0b3da4a5daabe97a1fd7a9cebc09d015f26e50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - dash  # not listed in the setup.py but required to import dash_html_components

test:
  requires:
    - pip
  imports:
    - dash_html_components
  commands:
    - pip check

about:
  home: https://github.com/plotly/dash-html-components
  dev_url: https://github.com/plotly/dash-html-components
  doc_url: https://github.com/plotly/dash-html-components/blob/dev/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Dash UI HTML component suite'
  description: 'Dash UI HTML component suite'

extra:
  recipe-maintainers:
    - moorepants
