travis:
  secure:
    BINSTAR_TOKEN: QYG7vTAEtPTnaD7NpRB3fpAZI5+6nCaV+Q1shiKKaIGYaN1Z06Do2cAX6kunLAv7bQZU58yGwesKJfWJi1QMF7kjqynmOAUyoJNuFLZ5GJBguTiSBZi/+Wabjqa8mP+MFabfr6wjJc9DmVzvlWo42EIW7RrLR7Flt/LxqCUAbckcBXXAvsttsYXpnsvDUWXwa4BsApeGmsuWCf6Fh0WbmWAFfY41wdK/eiGCAJoAAts9Gf4j6JuOIb7ArWny3Tj7v4O350dz/PnRwnd8WMnMYTWFZexUbcel3gz9gvYb5DvKW6tEtm1tObmB20wTJfl8UspU+Nc3nl7rIk0euhGcMXgWu1mngt0R3Mz57dG81l0CT0mD1pRbYEVy8nPip5RohB/sUVWdwDezfr8oE2BSd9YDt8NgvF/J22Chfy5O95UfVXGCp3MmxBZbJvhAH5jAKbDfkM50EoVTKtgqT4ZtEd+7c6/DkARSuNUQqGCpM6twYnOZpaMMtAd287Ir9LCsDmyrzOkYk6iV0avDgKLUSNg6avFxEneiA9dz3aoHytmQ3lmOoIno619Ld9jnH2conq0wcSr3meDImdojb3gkoKVnPuAx3OB/Pq2VHuHr8K0qNh78OEnIS1W0YkGsc30Ct1RpUCm2ZkO0K79P98gTClLwE2Z670bhRnlqA1JP/Ds=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
