travis:
  secure:
    BINSTAR_TOKEN: aVi7bgkxATdC3uf+jLMJLNbbOjiatefnZKjAcLaBbxyO/pqFaJTuE+e7kpn40QIjIo48fy3zWAsO+6+LmLl0qr7oFF2X/Ei20q+XperxYL/6Y7j8AK9DCn8VlEsRfgxsEZIcpJ6e+HJRWluYHq/Ig9t2Is07aHs5gM+T0vf2GNMxbosM9CV4tBbMmVtpRfIxuvHUS9Rds3rYYV7yZG5Hqf6TGjNJQPKBX9SBNMVcqhOirKWaE6RbXnVi+EAv6E8mZPnNa1UzckEkmvCZQYFSB1mgcDCj7g60G9oZbARo5qV714ZXYVwS0yKE1GKRWTHrXkSAEjgmsNYw9oKjzZe0DEJ+lyyjmqDSL8D/qCp0gbZ32/p7EC1YqEqRBwt0lgR+gLy0wYsUD32CNegvYYtS0D72B02Kh+mqCKau8dtioUyCvT4Ojh/jiq04fgmtfJjbzSgHlXADY5VRv06ILUYP+nMN4n5EJONj3a7gGEe7GzMv/9B7GSe7PmHMv/QdLwtf+iSITC65CPT2cLCfa8LdL+9nwmlTTY4nTCEvEZfkeVmz1C1YZqroeklCEae8+ywpnTU2f6OloXWuANr1L2LrWnHWH2Sthen0MwuFTOZNGhU8DodycZSLfeCMvOztX9HdpJKNQskW41psY0zQZhecCgEG0shvfocZWFPudIyJDAs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
